### ISSUE TITLE
Incorrect indentation in a couple places

### ISSUE THREAD

**Issue by dtauxe** [nachumk/systemverilog.vim#14]
**1)** ``function`` and ``task`` declared as ``extern`` still increase indent:
```
class Class1:
   extern function void foo();
      extern task bar();
         // Not so great
      endclass
```

**2)** This strange error popped up while concatenating strings.
Block is not indented:
```
if (a == b)
begin
foo = {"bar",func("baz")};
end
```

From what I've found, spacing doesn't matter. Whether ``begin`` is on the line with ``if`` or not doesn't matter. If this is in a task, begin/end are not required. Interestingly, without those and not inside a block, any indent will be accepted unchanged.

_Both_ of those arguments must be strings, and the _second_ one must have parens around it. Switching around parens and braces makes no difference. The comma doesn't matter. So a minimal-character but not real example for that line is ``{""("")}``.

**Comment by nachumk** [comment]
Fixed in 1.11.1
