### ISSUE TITLE
Unpleasant behavior b/c inline editing causes spurious shifting.

### ISSUE THREAD

**Issue by nachumk** [nachumk/systemverilog.vim#3]
begin
 a = (b || c);
end
Now go back and edit line 2 by expanding 'c' into '(c || d)'. If you start from the end first by adding the extra parenthesis first (')'), then the line will shift left. This is annoying. It will fix itself when the extra right parenthesis ('(') is added. This problem could be fixed by differentiating which indent openers and closers are used. For example, if the indentation is caused by 'begin', then only 'end' should bring the indent back.

**Comment by Walkermoon** [comment]
True. Please fix this if possible.

**Comment by nachumk** [comment]
Fixed.
