### ISSUE TITLE
IF ELSE indent issues,$display problem

### ISSUE THREAD

**Issue by vineethsukumar** [nachumk/systemverilog.vim#4]
If I am writing the code below it is not indented properly

if(a) begin
  c=1;
  d=1;
  else begin
    c=0;
    d=0;
  end

else is coming directly under d.It is not shifted to the left.Because of that end is also misplaced.
It would be nice if else can be shifted to the left automatically.Same in the case of end

$display 
is not showing as a keyword...

**Comment by nachumk** [comment]
$display added in v1.6
