### ISSUE TITLE
Folding the code

### ISSUE THREAD

**Issue by vineethsukumar** [nachumk/systemverilog.vim#5]
Is there any way to introduce folding to the code.If it is there it would be much more easier to write codes.

**Comment by nachumk** [comment]
I don't know anything about that... If you submit a fix, I'd be happy to merge it in.

**Comment by nachumk** [comment]
I'd add this to your .vimrc if you want to use folding:
set foldmethod=indent   
set foldnestmax=10
set nofoldenable
set foldlevelstart=10
