### ISSUE TITLE
change systemverilog.vim to verilog_systemverilog.vim

### ISSUE THREAD

**Issue by nadaved1** [nachumk/systemverilog.vim#8]
Hi Noam,
I think you need to change .vim/syntax/systemverilog.vim to .vim/syntax/verilog_systemverilog.vim. otherwise the plugin doesn't work.

Thanks,
Nadav.

**Comment by nachumk** [comment]
Perhaps, but I chose to use the name systemverilog in ftdetect. So it works fine using that.

Noah

**Comment by nachumk** [comment]
Closing unless there is a compelling reason to change the name.
